name: Basic CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-checks:
    name: Check Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies (if any)
        run: |
          cd backend
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run backend linter (flake8 placeholder)
        run: |
          cd backend
          echo "Skipping actual linting for now"

      - name: Run backend tests (placeholder)
        run: |
          cd backend
          echo "No backend tests yet"

  # frontend-checks:
  #   name: Check Frontend
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20

  #     - name: Install frontend dependencies (if any)
  #       run: |
  #         cd frontend
  #         if [ -f package.json ]; then
  #           npm install
  #         fi

  #     - name: Run frontend linter (placeholder)
  #       run: |
  #         cd frontend
  #         echo "Skipping linting for now"

  #     - name: Run frontend tests (placeholder)
  #       run: |
  #         cd frontend
  #         echo "No frontend tests yet"
